name: Docker Build with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform & cache)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub (optional, remove if not pushing)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with cache
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile  # Adjust if in subdirectory
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ayesa-java-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ayesa-java-api:${{ github.sha }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}